# Generated by Django 5.0.1 on 2024-01-17 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="Background",
            field=models.ImageField(default="", upload_to="bg_images"),
        ),
        migrations.AddField(
            model_name="newpost",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
