# Generated by Django 4.1.13 on 2024-01-15 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0003_newpost_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newpost",
            name="title",
        ),
    ]
